### ISSUE TITLE
Basic help

### ISSUE THREAD

**Issue by ttunguz** [jakubnowicki/r-codespaces#6]
Thanks so much for putting this together. I copied your devcontainer-json folder and put it into my root directory of my github repo that has codespaces enabled. I waited for 30 mins for the session to time out and then spun it up, but I still get the message “linux can’t use R” when I execute my R code. 

What am I doing wrong? Thanks

**Comment by jakubnowicki** [comment]
Ok, I've just checked and I was able to create a new codespace with working R for this repo, so this should not be a dependency issue. Can you send more details?
Have you tried running it again? It sometimes gets stuck for some random reason.
Besides that, please make sure that:
- you have copied a whole `.devcontainer` directory.
- you are using correct branch (with codespaces configuration)
- after adding configuration you have started fresh codespace

Please let me know if you were able to run your R code.

**Comment by ttunguz** [comment]
Thanks for the help. If I fork the repo and then create a codespace on top, it works fantastic. I have a big library of R  scripts already. What’s the best way to configure your R repo to work with that? Thanks for helping me.

**Comment by ttunguz** [comment]
Actually, I figured it out. Cloned the repo, and then copied in the files. Thanks for the help and the excellent config help!
